### PR TITLE
Fix various linter errors

### PR DESCRIPTION
**Pull request by SuperQ**
Fix a number of issues found by golangci-lint.

### CODE REVIEW

**Comment by SuperQ** [comment]
Ok, I've reduced the linter errors to this list:

```
stuff/dbbackend.go:266:16: Error return value of `d.joinSet.Exec` is not checked (errcheck)
	d.joinSet.Exec(id, set)
	              ^
stuff/dbbackend.go:276:18: Error return value of `d.leaveSet.Exec` is not checked (errcheck)
		d.leaveSet.Exec(id, c.Equiv_set)
		               ^
stuff/search-handler.go:175:16: Error return value of `pusher.Push` is not checked (errcheck)
				pusher.Push(imgUrl, nil)
				           ^
```

**Review by hzeller — APPROVED** [review]

**Comment by hzeller** [comment]
How can I run the linter locally ?

**Comment by SuperQ** [comment]
https://golangci-lint.run/usage/install/#local-installation

**Comment by hzeller** [comment]
Ah nice. I found that `golangci-lint` is available in nix already and now [added linting](https://github.com/hzeller/stuff-org/commit/0fcc722182abe0ac02a67ff047417002d349b723).

**Comment by SuperQ** [comment]
Cool, I can add it to the actions once all the current issues are fixed.

**Comment by hzeller** [comment]
Alright, lint is now happy,

**Pull request merged**
